import { useEffect, useRef, useState } from "react";
import { useParams, Link } from "react-router-dom";
import axios from "axios";
import toast from "react-hot-toast";
import jsPDF from "jspdf";
import { QRCodeCanvas } from "qrcode.react";

export default function TicketPage() {
  const { registrationId } = useParams();
  const [ticket, setTicket] = useState(null);
  const [loading, setLoading] = useState(true);
  const qrRef = useRef(null);

  useEffect(() => {
    let mounted = true;
    const loadTicket = async () => {
      try {
        const response = await axios.get(
          `http://localhost:3000/api/tickets/registration/${registrationId}`
        );
        if (!mounted) return;
        setTicket(response.data);
      } catch (error) {
        console.error("Error loading ticket:", error);
      } finally {
        if (mounted) setLoading(false);
      }
    };
    loadTicket();
    return () => { mounted = false; };
  }, [registrationId]);

  const downloadQR = () => {
    const canvas = qrRef.current?.querySelector("canvas");
    if (!canvas) return;
    const url = canvas.toDataURL("image/png");
    const a = document.createElement("a");
    a.href = url;
    a.download = `qr-${ticket.ticketNumber}.png`;
    a.click();
    toast.success("QR Code downloaded!");
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFillColor(28, 28, 26);
    doc.rect(0, 0, 210, 297, "F");
    doc.setFontSize(24);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text("EVENT TICKET", 105, 40, { align: "center" });
    doc.setDrawColor(255, 255, 255, 0.2);
    doc.line(20, 50, 190, 50);
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(200, 200, 200);
    doc.text(`Event   : ${ticket.registration?.event?.title || "N/A"}`, 20, 70);
    doc.text(`Date    : ${ticket.registration?.event?.date || "N/A"}`, 20, 85);
    doc.text(`Time    : ${ticket.registration?.event?.time || "N/A"}`, 20, 100);
    doc.text(`Venue   : ${ticket.registration?.event?.venue?.name || "N/A"}`, 20, 115);
    doc.text(`Student : ${ticket.registration?.user?.name || "N/A"}`, 20, 130);
    doc.line(20, 145, 190, 145);
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text(`Ticket # : ${ticket.ticketNumber}`, 20, 165);
    doc.setFontSize(13);
    doc.setTextColor(100, 220, 100);
    doc.text(`Status   : ${ticket.status}`, 20, 182);

    // Embed QR image into PDF
    const canvas = qrRef.current?.querySelector("canvas");
    if (canvas) {
      const qrDataUrl = canvas.toDataURL("image/png");
      doc.addImage(qrDataUrl, "PNG", 20, 195, 60, 60);
    }

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("This ticket is generated by Event Management System", 105, 280, { align: "center" });
    doc.save(`ticket-${ticket.ticketNumber}.pdf`);
    toast.success("Ticket downloaded!");
  };

  if (loading) {
    return (
      <div className="rounded-2xl border border-white/10 bg-[#1c1c1a] p-6 text-white/70">
        Loading ticket...
      </div>
    );
  }

  if (!ticket) {
    return (
      <div className="rounded-2xl border border-white/10 bg-[#1c1c1a] p-6">
        <p className="text-white/70">Ticket not found or not yet generated.</p>
        <Link to="/student/registered-events" className="mt-4 inline-block rounded-xl border border-white/15 px-4 py-2 text-sm text-white/80 hover:text-white">
          Back to Registrations
        </Link>
      </div>
    );
  }

  if (ticket.status === "CANCELLED") {
    return (
      <div className="rounded-2xl border border-red-400/30 bg-[#1c1c1a] p-6">
        <h2 className="text-xl font-semibold text-white">🎟️ Your Ticket</h2>
        <div className="mt-4 rounded-xl border border-red-400/30 bg-red-400/10 px-4 py-3 text-sm text-red-300">
          ❌ Your ticket has been cancelled. Please contact admin.
        </div>
        <Link to="/student/registered-events" className="mt-4 inline-block rounded-xl border border-white/15 px-4 py-2 text-sm text-white/80 hover:text-white">
          Back to Registrations
        </Link>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-white/10 bg-[#1c1c1a] p-6 shadow-[0_12px_28px_rgba(0,0,0,0.25)]">

      {/* Header */}
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-semibold text-white">🎟️ Your Ticket</h2>
        <span className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-medium text-emerald-200">
          {ticket.status}
        </span>
      </div>

      {/* Event Info */}
      <div className="mt-5 rounded-xl border border-white/10 bg-[#111110] p-4">
        <h3 className="text-lg font-semibold text-white">
          {ticket.registration?.event?.title || "N/A"}
        </h3>
        <div className="mt-3 grid grid-cols-1 gap-2 text-sm text-white/70 sm:grid-cols-2">
          <p>Date   : {ticket.registration?.event?.date || "N/A"}</p>
          <p>Time   : {ticket.registration?.event?.time || "N/A"}</p>
          <p>Venue  : {ticket.registration?.event?.venue?.name || "N/A"}</p>
          <p>Student: {ticket.registration?.user?.name || "N/A"}</p>
        </div>
      </div>

      {/* Ticket Info */}
      <div className="mt-4 rounded-xl border border-white/10 bg-[#111110] p-4">
        <p className="text-sm text-white/60">Ticket Number</p>
        <p className="mt-1 text-2xl font-bold text-white tracking-widest">
          {ticket.ticketNumber}
        </p>

        <p className="mt-4 text-sm text-white/60">QR Code</p>
        <div ref={qrRef} className="mt-2">
          <QRCodeCanvas
            value={ticket.qrCode}
            size={150}
            bgColor="#111110"
            fgColor="#ffffff"
          />
        </div>
      </div>

      {/* Buttons */}
      <div className="mt-6 flex flex-wrap gap-3">
        <button
          onClick={downloadPDF}
          className="rounded-xl bg-sky-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-sky-500"
        >
          ⬇️ Download PDF
        </button>

        <button
          onClick={downloadQR}
          className="rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-emerald-500"
        >
          🔲 Download QR
        </button>

        <Link
          to="/student/registered-events  "
          className="rounded-xl border border-white/15 px-4 py-2 text-sm text-white/80 hover:text-white"
        >
          Back to Registrations
        </Link>
      </div>

    </div>
  );
}